# Generated by Django 5.2.7 on 2025-10-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subTotall',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
