# Generated by Django 5.2.7 on 2025-10-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_cart_subtotall'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subTotall',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
