# Generated by Django 5.2.7 on 2025-10-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cart_subtotall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='subTotall',
        ),
    ]
