# Generated by Django 5.2.7 on 2025-11-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_cart_subtotall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='subTotall',
        ),
    ]
