# Generated by Django 5.2.3 on 2025-07-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catageory',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
