# Generated by Django 5.2.3 on 2025-08-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_oder_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myorder', to='myapp.order'),
        ),
    ]
