# Generated by Django 5.2.3 on 2025-08-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_oder_item_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder_item',
            new_name='OrderItem',
        ),
    ]
