# Generated by Django 5.2.5 on 2025-09-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=25)),
                ('categoryDesc', models.TextField(max_length=100)),
                ('categoryImage', models.ImageField(null=True, upload_to='category')),
            ],
        ),
    ]
