# Generated by Django 5.2.5 on 2025-09-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productCatg',
            new_name='Catg',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productDesc',
            new_name='Desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productImage',
        ),
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryImage',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
    ]
